version: '3.8'

services:
  workspace-service-db:
    container_name: workspace-service-db
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - workspace-service-db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 20
    ports:
      - "${DB_EXPOSE_PORT}:5432"
    networks:
      - mocha-network

  workspace-service:
    container_name: workspace-service
    build:
      context: .
      dockerfile: Dockerfile
    image: workspace-service:latest
    environment:
      PORT: ${PORT}
      SPRING_PROFILES_ACTIVE: docker
      KEYCLOAK_ENVIRONMENT: ${KEYCLOAK_ENVIRONMENT}
      KEYCLOAK_BASE_URI: ${KEYCLOAK_BASE_URI}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
    ports:
      - "${PORT}:${PORT}"
    networks:
      - mocha-network

networks:
  mocha-network:
    external: true

volumes:
  workspace-service-db-data: {}