-- Create accounts table
CREATE TABLE accounts (
      id UUID PRIMARY KEY,
      created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
      workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
      created_by UUID NOT NULL,
      balance NUMERIC(19, 4) NOT NULL DEFAULT 0,
      name VARCHAR(255) NOT NULL,
      display_name VARCHAR(255),
      currency VARCHAR(3) NOT NULL DEFAULT 'USD' CHECK (currency IN ('USD', 'EUR', 'GBP', 'CAD', 'AUD', 'JPY')),
      institution_name VARCHAR(255),
      status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'ARCHIVED')),
      source VARCHAR(20) NOT NULL DEFAULT 'MANUAL' CHECK (source IN ('MANUAL', 'AUTOMATIC')),
      type VARCHAR(255) NOT NULL CHECK (type IN ('CASH', 'CREDIT', 'INVESTMENT', 'LOAN', 'REAL_ESTATE', 'VEHICLE', 'EMPLOYEE_COMPENSATION', 'OTHER_LIABILITY', 'OTHER_ASSET')),
      sub_type VARCHAR(255) NOT NULL CHECK (sub_type IN (
          'CHECKING', 'SAVINGS', 'DIGITAL_WALLET', 'GIFT_CARD', 'PHYSICAL_CASH', 'OTHER_CASH',
          'CREDIT_CARD', 'CHARGE_CARD', 'LINE_OF_CREDIT', 'OTHER_CREDIT',
          'RETIREMENT', 'EDUCATION_SAVINGS', 'BROKERAGE', 'HEALTH_SAVINGS', 'OTHER_INVESTMENT',
          'MORTGAGE', 'AUTO_LOAN', 'STUDENT_LOAN', 'PERSONAL_LOAN', 'OTHER_LOAN',
          'PRIMARY_RESIDENCE', 'INVESTMENT_PROPERTY', 'LAND', 'OTHER_REAL_ESTATE',
          'CAR', 'TRUCK', 'MOTORCYCLE', 'BOAT', 'RV', 'OTHER_VEHICLE',
          'STOCK_OPTIONS', 'RESTRICTED_STOCK', 'ESPP', 'BONUS', 'OTHER_COMPENSATION',
          'TAXES_PAYABLE', 'MEDICAL_BILL', 'LEGAL_OBLIGATION', 'OTHER_LIABILITY',
          'JEWELRY', 'COLLECTIBLE', 'LIFE_INSURANCE_CASH_VALUE', 'OTHER_ASSET'
      ))
);